# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - run: run isort --recursive --diff
      - run: run black --check .
      - run: run flake8
      - run: run mypy
      - run: run pytest --cov --cov-fail-under=100
